name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master  # Ensure this matches the branch you are using for GitHub Pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build and deploy
      uses: helaili/jekyll-action@2.0.4
      env:
        JEKYLL_PAT: ${{ secrets.GITHUB_TOKEN }}
